# Generated by Django 3.0.8 on 2020-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
