# Generated by Django 3.0.8 on 2020-07-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travellers', '0002_traveller_is_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='email',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveller',
            name='price_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
