# Generated by Django 3.0.8 on 2020-07-30 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travellers', '0003_auto_20200730_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
